name: starter_architecture_flutter
description: Fluter architecture template with riverpod + go_router

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Http client
  dio: ^5.3.3
  # State management
  flutter_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  # Navigation
  go_router: ^12.0.1
  # Preferences
  shared_preferences: ^2.2.2
  # Serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  # Assets
  animate_do: ^3.1.2
  cupertino_icons: ^1.0.6
  # Utils
  mask_text_input_formatter: ^2.5.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Code generation
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  riverpod_generator: ^3.0.0-dev
  go_router_builder: ^2.3.4
  #  Lints
  flutter_lints: ^3.0.0
  riverpod_lint: ^2.3.3
  custom_lint: ^0.5.5

scripts: derry.yaml

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
